available_text_models: ["gpt-3.5-turbo", "gpt-4o"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: GPT-3.5 Turbo
    description: The GPT-3.5 Turbo model is a fast, inexpensive model for simple tasks. It has a 16K context window and is optimized for dialog.

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is OpenAI's <b>most advanced</b> multimodal model that’s faster and cheaper than GPT-4 Turbo with stronger <b>vision capabilities</b>. The model has 128K context and an October 2023 knowledge cutoff.

    scores:
      Smart: 5
      Fast: 4
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006