available_text_models: ["gpt-4o-mini", "gpt-4o"]

info:
  gpt-4o-mini:
    type: chat_completion
    name: GPT-4o mini
    description: GPT-4o mini is OpenAI's <b>most cost-efficient</b> small model that’s smarter and cheaper than GPT-3.5 Turbo, and has vision capabilities. The model has 128K context and an October 2023 knowledge cutoff.

    scores:
      Smart: 4
      Fast: 5
      Cheap: 5

  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is OpenAI's <b>most advanced</b> multimodal model that’s faster and cheaper than GPT-4 Turbo with stronger <b>vision capabilities</b>. The model has 128K context and an October 2023 knowledge cutoff.

    scores:
      Smart: 5
      Fast: 4
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006